// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKNoWdfBFaVfH4D_caD-aUlvf3x0n1tFg',
    appId: '1:118053547334:web:b05199acaa7f535866c947',
    messagingSenderId: '118053547334',
    projectId: 'emax-e817a',
    authDomain: 'emax-e817a.firebaseapp.com',
    storageBucket: 'emax-e817a.appspot.com',
    measurementId: 'G-FRRGW29JRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Z5Vzn8JHSaZ3dxgCKcnja9O9NP4wsYI',
    appId: '1:118053547334:android:4780ef925b260be366c947',
    messagingSenderId: '118053547334',
    projectId: 'emax-e817a',
    storageBucket: 'emax-e817a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO8_BQhyALmufPl_G7sYxtQSwYonDa6Ks',
    appId: '1:118053547334:ios:28fc3ab50778877266c947',
    messagingSenderId: '118053547334',
    projectId: 'emax-e817a',
    storageBucket: 'emax-e817a.appspot.com',
    androidClientId: '118053547334-pohf6qek0lshf9t4vcr3hhjftp5ifnb0.apps.googleusercontent.com',
    iosClientId: '118053547334-400oqkjsaocemm8qatceosgn3go13182.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO8_BQhyALmufPl_G7sYxtQSwYonDa6Ks',
    appId: '1:118053547334:ios:28fc3ab50778877266c947',
    messagingSenderId: '118053547334',
    projectId: 'emax-e817a',
    storageBucket: 'emax-e817a.appspot.com',
    androidClientId: '118053547334-pohf6qek0lshf9t4vcr3hhjftp5ifnb0.apps.googleusercontent.com',
    iosClientId: '118053547334-400oqkjsaocemm8qatceosgn3go13182.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKNoWdfBFaVfH4D_caD-aUlvf3x0n1tFg',
    appId: '1:118053547334:web:8aaeb24b6087e88966c947',
    messagingSenderId: '118053547334',
    projectId: 'emax-e817a',
    authDomain: 'emax-e817a.firebaseapp.com',
    storageBucket: 'emax-e817a.appspot.com',
    measurementId: 'G-M6L07ZPP4E',
  );
}
