name: final_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.1.2
  flutter_svg: ^2.0.10
  font_awesome_flutter: ^10.7.0
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_core_dart: ^1.0.1
  firebase_analytics: ^10.4.5
  cloud_firestore: ^4.17.3
  email_validator: ^2.1.17
  google_sign_in: ^5.4.2
  quickalert: ^1.1.0
  image_picker: ^1.1.1
  firebase_database: ^10.5.5
  flutter_tts: ^4.0.2
  toastification: ^2.0.0
  fluttertoast: ^8.2.5
  flutter_slidable: ^3.1.0
  file_picker: ^4.0.0
  csv: ^5.0.0
  path_provider: ^2.0.15
  path: ^1.9.0
  permission_handler: ^11.3.1
  firebase_storage: ^11.7.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/clock.png
    - assets/images/light-1.png
    - assets/images/light-2.png
    - assets/images/Bg.png
    - assets/images/line.svg
    - assets/images/oval.svg
    - assets/images/BgLogIn.png
    - assets/images/bgforgot.png
    - assets/images/avt.png
    - assets/images/path.svg
    - assets/images/saturn.png
    - assets/images/telescope.png
    - assets/images/home.png
    - assets/images/profile.png
    - assets/images/bg3.jpeg
    - assets/images/bg4.avif
    - assets/images/search.png
    - assets/images/bgcard1.png
    - assets/images/bgcard2.png
    - assets/images/bgcard3.png
    - assets/images/next.png
    - assets/images/food.png
    - assets/images/drink.png
    - assets/images/animal.png
    - assets/images/library.png
    - assets/images/library2.png
    - assets/images/library3.png
    - assets/images/topic.png
    - assets/images/category1.png
    - assets/images/return.png
    - assets/images/google.png
    - assets/images/multichoice.png
    - assets/images/flashCard.png
    - assets/images/flashCard1.png
    - assets/images/type.png
    - assets/images/raucu.png
    - assets/images/ranking.png
    - assets/images/rankPage.png
  fonts:
    - family: Alpenable
      fonts:
        - asset: assets/fonts/alpenable.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
    - family: Nunito-Italic
      fonts:
        - asset: assets/fonts/Nunito-Italic.ttf
    - family: Nunito-Bold
      fonts:
        - asset: assets/fonts/NunitoB.ttf
